### ISSUE TITLE
Running Docker Build 

### ISSUE THREAD

**Issue by izdrail** [mralston/laravel-docker#1]
So I'm trying to build a image from a laravel app that I've created using your docker basics
When I run 

`docker build . -t news-app -f docker/php/php.Dockerfile
`
The image builts succesfully 
But when I try to run the built image   
I get :

`CONTAINER_ROLE not recognised!
Check environment variable in docker-compose.yml.`

This error comes from the start-container.sh
any ideea how could I fix it ?

**Comment by mralston** [comment]
You need to add an environment variable for each PHP container in your `docker-compose.yml` file, e.g.

```
php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      CONTAINER_ROLE: php
```

Possible values are:

- php
- queue
- scheduler

**Comment by izdrail** [comment]
You can see the project at 
https://github.com/lzomedia/articles


``` yaml
version: '3'
networks:
  laravel:
    external: true

volumes:
  database:

services:
  database:
    image: mysql:latest
    restart: "no"
    volumes:
      - ./docker/database/init:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    ports:
      - ${DB_EXT_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: nginx
    depends_on:
      - php # PHP container must be started before NGINX
      - database # MySQL container must be started before NGINX
    ports:
      - 80:80
    volumes:
      - .:/site:cached

  php:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    image: php
    depends_on:
      - redis
      - database
    volumes:
      - .:/site:cached
      - database:/var/lib/mysql
    env_file:
      - docker/php/env
    environment:
      CONTAINER_ROLE: php

  queue:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    image: php
    depends_on:
      - php
      # NGINX needs to start before queue so that its IP can be resolved
      # and added to /etc/hosts for PhantomJS
      - nginx
      - redis
    restart: always
    volumes:
      - .:/site:cached
    env_file:
      - docker/php/env
    environment:
      CONTAINER_ROLE: queue

  scheduler:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    image: php
    depends_on:
      - php # scheduler 'extends' php, so build php first
      - redis
    restart: always
    volumes:
      - .:/site:cached
    env_file:
      - docker/php/env
    environment:
      CONTAINER_ROLE: scheduler

  redis:
    image: redis:latest

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - 8025:1080
      - 1080:1080
```
